### ISSUE TITLE
 MetaMask Web3 object

### ISSUE THREAD

**Issue by aravind1705** [nottoobright/VotingDecentralized#1]
How do I solve these issues in the project?

**Uncaught Error**: The MetaMask Web3 object does not support synchronous methods like eth_call without a callback parameter.

**Uncaught Error**: Invalid number of arguments to Solidity function

**Comment by nottoobright** [comment]
Metamask is pretty strict with how it compiles its code. That's why I'm
creating a custom Node project as a boilerplate for all my future Ethereum
based projects.

The error states that you cannot call a function on your contract without a
callback parameter. So do exactly that. Instead of doing a
contractName.function.call()

Do this --> 
contractName.function.call((err, res) => {
//interact with the res object and handle err
}


For invalid number of arguments, check which type are the required arguments and be sure to include them. 
Hopefully this solves your issue

**Comment by aravind1705** [comment]
Thank you. 
I'll look into it.
